version: '3.7'
services:
  app:
    logging:
      driver: 'json-file'
      options:
        max-size: '8000k'
        max-file: '10'
    restart: always
    image: node:15.13.0-alpine3.10
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: sh -c 'npm i && node ace token:watch'
  redis:
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    image: 'redis:alpine'
    volumes:
      - ../data/redis:/var/lib/redis
volumes:
  data:
    driver: local
  logs:
    driver: local
